version: '3'
services:
  app:
    build: .
    ports:
      - "80:80"
      - "5000:5000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
