version: '3'

services:
  frontend:
    build:
      context: ./eCommerce_Reactjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./ecomAPI
      dockerfile: Dockerfile
    ports:
      - "5000:5000"